# Generated by Django 2.2.2 on 2021-01-28 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0006_delete_viewcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.SlugField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('posts', models.ManyToManyField(null=True, to='blog.Post')),
            ],
        ),
    ]
