# Generated by Django 2.2.2 on 2021-01-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttag',
            name='posts',
            field=models.ManyToManyField(to='blog.Post'),
        ),
    ]
