# Generated by Django 2.2.2 on 2021-02-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_auto_20210201_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttag',
            name='tag_name',
            field=models.CharField(max_length=50),
        ),
    ]
