# Generated by Django 2.2.2 on 2021-02-01 05:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0004_auto_20210201_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttag',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
