# Generated by Django 2.2.2 on 2021-01-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210113_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_num',
            field=models.IntegerField(default=0),
        ),
    ]
