# Generated by Django 2.2.2 on 2021-01-15 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_view_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='view_num',
            new_name='view_count',
        ),
    ]
