# Generated by Django 2.2.2 on 2021-01-17 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210115_0653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewCount',
        ),
    ]
